"Name: \PR:SAPLCOMD\FO:SCREEN_MODIFY_PM\SE:BEGIN\EI
ENHANCEMENT 0 ZLCOMDF30.
*
  LOOP AT SCREEN.
    IF screen-name = 'RESBD-EKGRP'.
      screen-group2 = ''.
    ENDIF.
  MODIFY SCREEN.
  ENDLOOP.

ENDENHANCEMENT.
