"Name: \FU:EQUIPMENT_SAVE\SE:BEGIN\EI
ENHANCEMENT 0 ZPM_EQUIPMENT_SAVE.
*
break sahmad.
TRANSLATE C_OBJECT_REC-herst TO UPPER CASE.
TRANSLATE C_OBJECT_REC-typbz TO UPPER CASE.
TRANSLATE C_OBJECT_REC-mapar TO UPPER CASE.
TRANSLATE C_OBJECT_REC-serge TO UPPER CASE.

ENDENHANCEMENT.
